'use strict';

export const LOADING = 'LOADING';
export const CREATERECIPE = 'CREATERECIPE';
export const FINDRECIPES = 'FINDRECIPES';
export const VIEWRECIPE = 'VIEWRECIPE';
export const EXTRACTWEBSITE = 'EXTRACTWEBSITE';

export const ONLINERECIPEADDED = 'ONLINERECIPEADDED';
export const ONLINERECIPEREMOVED = 'ONLINERECIPEREMOVED';

export const ADDONLINERECIPE = 'ADDONLINERECIPE';
export const REMOVEONLINERECIPE = 'REMOVEONLINERECIPE';

export const ADDLOCALRECIPE = 'ADDLOCALRECIPE';
