'use strict';

export const LOADING = 'LOADING';
export const LOADINGWEBSITE = 'LOADINGWEBSITE';
export const CREATERECIPE = 'CREATERECIPE';
export const FINDRECIPES = 'FINDRECIPES';
export const VIEWRECIPE = 'VIEWRECIPE';
export const EXTRACTWEBSITE = 'EXTRACTWEBSITE';
export const RESET = 'RESET';

export const ONLINERECIPEADDED = 'ONLINERECIPEADDED';
export const ONLINERECIPEREMOVED = 'ONLINERECIPEREMOVED';
export const LOCALRECIPEADDED = 'LOCALRECIPEADDED';
export const LOCALRECIPEREMOVED = 'LOCALRECIPEREMOVED';

export const ADDONLINERECIPE = 'ADDONLINERECIPE';
export const REMOVEONLINERECIPE = 'REMOVEONLINERECIPE';

export const ADDLOCALRECIPE = 'ADDLOCALRECIPE';
